// 화면 설명서 주석 데이터 (한글)
// 구조: screen -> sig -> { t:요소명, r:역할, a:동작, c:조건·예외 }
// 코드(claims.js/common.js/intake.js/images.js/closing.js/assign.js/ai-dashboard.js/message.js/vendor.js 및 각 inline)에서 확인한 내용 기준.
// 코드만으로 단정하기 어려운 부분은 (추정) 표기.
module.exports = {
  index: {
    'a|href|smart-claims.html': { t:'미결일괄조회 카드', r:'사고건 단계별 통합 업무 리스트 진입', a:'클릭 시 smart-claims.html 로 이동', c:'—' },
    'a|href|smart-intake.html': { t:'Smart업무처리 카드', r:'사고 접수·계약·견적·결재 상세 진입', a:'클릭 시 smart-intake.html 로 이동', c:'—' },
    'a|href|image-system.html': { t:'이미지시스템 카드', r:'차량·사고 사진 관리 진입', a:'클릭 시 image-system.html 로 이동', c:'—' },
    'a|href|approval-list.html': { t:'결재 LIST 카드', r:'추산·지급 결재 진행 현황 진입', a:'클릭 시 approval-list.html 로 이동', c:'—' },
    'a|href|assignment-management.html': { t:'전결·순환배당 관리 카드', r:'전결권한·순환배당 규칙 설정 진입', a:'클릭 시 assignment-management.html 로 이동', c:'—' },
    'a|href|vendor-inquiry.html': { t:'협력업체조회 카드', r:'협력업체 계약·수가·지급처 관리 진입', a:'클릭 시 vendor-inquiry.html 로 이동', c:'—' },
    'a|href|ai-dashboard.html': { t:'AI 통합대시보드 카드 (Pro)', r:'AI 견적·손해사정 심사/검토회신 진입', a:'클릭 시 ai-dashboard.html 로 이동', c:'Pro 버전 기능 표기' },
    'a|href|smart-claims-demo.html': { t:'자동처리 시연 카드 (Pro)', r:'자동 처리 흐름 애니메이션 시연 진입', a:'클릭 시 smart-claims-demo.html 로 이동', c:'시연 모드' },
  },

  'smart-claims': {
    'btnRequest': { t:'대차/탑승 신청 버튼', r:'렌트(대차)·탑승 신청 접수 진입', a:'클릭 시 신청 모달(openRequestModal) 열림. 선택된 사고건이 있으면 해당 ID 프리셋. 신청 완료 시 "{ID} 신청이 접수되었습니다" 토스트', c:'선택 사고 없으면 프리셋 없이 열림' },
    'a|href|smart-claims-demo.html': { t:'모드변경·시연 링크', r:'자동처리 시연 화면 전환', a:'클릭 시 smart-claims-demo.html 로 이동', c:'—' },
    'stageSelect': { t:'Flow 단계 선택 드롭다운', r:'처리 단계 필터(접수·선견적/수리승인/손해사정/지급·정산)', a:'change 시 setStage() 호출 → 조치유형 전체로 초기화, 1페이지로 이동, 카드·리스트 재렌더', c:'상단 Flow 카드와 상태 동기화' },
    'typeAll': { t:'조치유형 전체 체크박스', r:'현재 단계의 모든 조치유형 on/off', a:'체크 시 checkedTypes=해당 단계 전체, 해제 시 빈 집합', c:'개별 유형이 모두 체크되면 자동 on' },
    'input|checkbox|': { t:'개별 조치유형 체크박스 (면허미확인·계약조사 등)', r:'조치유형별 리스트 필터', a:'토글 시 checkedTypes 갱신, 1페이지·재렌더', c:'(반복) 전체 상태에서 개별 해제 시 나머지만 표시' },
    'btnReset': { t:'초기화 버튼', r:'검색 필터 초기화', a:'조치유형·계획·정비공장명·검색어·금액대 초기화 후 renderAll', c:'현재 단계(activeStage)는 유지' },
    'btnSearch': { t:'조회 버튼', r:'현재 조건으로 재조회', a:'1페이지 이동·selectFirst·renderList', c:'입력값은 실시간 반영되므로 확정 트리거 성격' },
    'shopInput': { t:'정비공장명 like검색 입력', r:'정비공장명 부분검색', a:'input 시 즉시 필터(shopQuery), 1페이지', c:'—' },
    'estMin': { t:'추산 금액대 하한 입력', r:'추산 금액 이상 조건', a:'입력 시 천단위 콤마 자동 서식, 숫자만 추출해 estMin 반영, 실시간 필터', c:'숫자 외 문자 제거' },
    'estMax': { t:'추산 금액대 상한 입력', r:'추산 금액 이하 조건', a:'입력 시 천단위 콤마 자동 서식, 숫자만 추출해 estMax 반영, 실시간 필터', c:'숫자 외 문자 제거' },
    'searchInput': { t:'통합 검색 입력(접수번호·차량명·차량번호·담당자)', r:'통합 like 검색', a:'input 시 실시간 필터, Enter 키로도 재조회', c:'—' },
    'button|button|': { t:'계획 필터 탭 (전체/★긴급/★관심)', r:'별점(계획) 상태로 리스트 필터', a:'클릭 시 planFilter=버튼값, selectFirst·재렌더', c:'(반복 x3)' },
    'button|button|cl-stat': { t:'Flow 단계 카드', r:'단계별 건수 표시 + 단계 필터', a:'클릭 시 setStage(dataset.stage) 로 해당 단계 필터', c:'(반복 x4) 활성 카드 강조' },
    'pageSizeSelect': { t:'페이지당 표시 건수 선택', r:'10/20/50개씩 보기', a:'change 시 pageSize 변경, 1페이지 재렌더', c:'기본 20개' },
    'selectAll': { t:'전체선택 체크박스', r:'현재 페이지 행 전체 선택', a:'체크 시 현재 페이지 항목을 selectedRows에 추가/제거', c:'현재 페이지 기준(전체 데이터 아님)' },
    'button|button|star-btn': { t:'계획(별점) 토글 버튼', r:'행별 긴급/관심 표시', a:'클릭 시 없음→긴급→관심→없음 순환(planState)', c:'(반복 x20) 계획 필터가 전체가 아니면 selectFirst 재수행' },
    'input|checkbox|row-check': { t:'행 선택 체크박스', r:'개별 사고건 선택', a:'토글 시 selectedRows 갱신, selectAll 동기화', c:'(반복 x20) 행 클릭 이벤트 전파 중단' },
  },

  'smart-intake': {
    'btnRequest': { t:'대차/탑승 신청 버튼', r:'렌트·탑승 신청 접수', a:'클릭 시 신청 모달 열림(공통)', c:'선택 사고건 프리셋' },
    'intakeBack': { t:'← 목록으로 버튼', r:'미결일괄조회로 복귀', a:'클릭 시 목록 화면으로 이동 (추정)', c:'—' },
    'intakeSearchBtn': { t:'🔍 검색 버튼', r:'사고건 조회', a:'클릭 시 runIntakeSearch 실행 → 좌측 조건으로 검색', c:'—' },
    'intakeResetBtn': { t:'↻ 재설정 버튼', r:'검색 조건 초기화', a:'클릭 시 검색 조건 리셋 (추정)', c:'—' },
    'intakeQueryType': { t:'조회 유형 선택', r:'검색 기준(사고번호/차량번호/피보험자/휴대폰 등)', a:'선택 후 입력값과 함께 검색', c:'—' },
    'input||lg-input': { t:'검색어 입력(사고번호 등)', r:'조회 유형에 대응하는 검색어', a:'값 입력 후 검색 실행', c:'—' },
    'intakeAttrSave': { t:'속성 저장 버튼', r:'미결속성/진행 메모 저장', a:'클릭 시 attrSave 핸들러로 속성 저장', c:'—' },
    'input|radio|': { t:'미결속성 라디오(재통화/방문 등)', r:'진행 조치유형 선택', a:'선택 시 해당 속성 활성화 (추정)', c:'(반복)' },
    'intakeMemoType': { t:'메모 대상 유형 선택', r:'통화·연락 상대(피보/정비공장/콜센터 등)', a:'선택 시 메모 대상 구분', c:'—' },
    'input|date|lg-attr-field': { t:'재통화 날짜 입력', r:'재통화 예정일', a:'날짜 지정 시 속성값 반영 (추정)', c:'—' },
    'button|button|lg-mini.gray': { t:'메세지발송 버튼', r:'대상에게 알림톡·문자 발송창 열기', a:'클릭 시 openMsgSendWindow 로 발송 창 오픈', c:'—' },
    'input|checkbox|': { t:'조치 체크박스(재통화 등)', r:'조치 항목 체크', a:'토글로 조치 상태 반영 (추정)', c:'(반복)' },
    'intakeMemoTarget': { t:'메모 대상자 입력', r:'통화/연락 대상 이름', a:'입력값 메모에 반영', c:'—' },
    'intakeMemoText': { t:'진행 내용 메모 입력', r:'진행 경과 기록', a:'텍스트 입력 후 메모 저장', c:'—' },
    'input|text|lg-attr-field': { t:'속성 입력 필드(탁송 메모 등)', r:'미결 속성 상세값', a:'입력값 속성에 반영 (추정)', c:'(반복) 최대 20자 등 필드별 제한' },
    'intakeMemoSave': { t:'메모 저장 버튼', r:'진행 메모 저장', a:'클릭 시 memoSave 핸들러 실행', c:'—' },
    'button|button|lg-tab': { t:'상세 탭(계약/사고 정보 등)', r:'상세 정보 영역 전환', a:'클릭 시 해당 탭 콘텐츠 표시', c:'(반복 x3) 활성 탭 강조' },
    'input|text|lg-cin': { t:'계약/사고 상세 입력 필드', r:'계약·사고 상세 정보 입력', a:'값 입력 시 상세 데이터 반영', c:'(반복)' },
    'ctPlaceSearch': { t:'지도에서 사고장소 검색 버튼', r:'사고장소 지도 검색', a:'클릭 시 장소 검색 실행 (추정)', c:'—' },
    'select||lg-csel': { t:'사고 유형 선택(차대차/차량단독 등)', r:'사고 형태 분류', a:'선택 시 사고 정보에 반영', c:'(반복)' },
    'ctAccDetail': { t:'사고 세부유형 선택', r:'세부 사고 상황(추돌/후진/주정차 등)', a:'선택 시 세부유형 반영', c:'—' },
    'ctMajorAcc': { t:'중대사고 구분 선택', r:'중앙선침범·침수·태풍 등 중대사고 여부', a:'선택 시 중대사고 항목 반영', c:'기본값 "선택"' },
    'input|text|lg-cin.lg-fault-in': { t:'과실비율 입력', r:'과실 비율 값', a:'숫자 입력 시 과실 정보 반영', c:'—' },
    'input|text|lg-cin.sm': { t:'경찰서명 등 소형 입력', r:'사고 접수 관련 부가정보', a:'입력값 반영', c:'(반복)' },
    'input|text|lg-cin.lg-drv-name': { t:'운전자명 입력', r:'운전자 성명', a:'입력값 반영', c:'—' },
    'ctDriverLookup': { t:'운전자 정보 조회 버튼', r:'운전자 정보 조회', a:'클릭 시 운전자 정보 조회 (추정)', c:'—' },
    'ctDriverCall': { t:'전화·문자 발송 버튼', r:'운전자 연락', a:'클릭 시 openMsgSendWindow 로 발송 창 오픈', c:'—' },
    'input|text|lg-cin.lg-birth-front': { t:'생년월일 앞자리 입력', r:'운전자 주민번호 앞자리', a:'입력값 반영', c:'개인정보 마스킹 표기' },
    'input|text|lg-cin.lg-birth-back': { t:'주민번호 뒷자리 첫자리 입력', r:'성별 구분자', a:'입력값 반영', c:'—' },
    'ctBirthAge': { t:'나이 표시/입력 필드', r:'운전자 연령', a:'생년월일 기준 산출 또는 입력 (추정)', c:'—' },
    'ctLicenseLookup': { t:'운전면허조회 버튼', r:'면허 진위/정보 조회', a:'클릭 시 fetchLicenseKooKoon 실행(외부 조회 연동)', c:'—' },
    'ctLicenseManual': { t:'직접입력 버튼', r:'면허 정보 수기 입력 전환', a:'클릭 시 면허 필드 수동 입력 모드 (추정)', c:'—' },
    'input|text|lg-cin.lg-drv-lno': { t:'운전면허번호 입력', r:'면허번호', a:'입력값 반영', c:'—' },
    'ctMsgBtn': { t:'알림톡·문자메세지 발송 버튼', r:'고객/운전자 메시지 발송', a:'클릭 시 openMsgSendWindow 로 발송 창 오픈', c:'—' },
    'ctCompFetch': { t:'타사 정보 조회 버튼', r:'상대(타사) 보험 정보 조회', a:'클릭 시 fetchCompetitorInfo 실행', c:'—' },
    'intakeSave': { t:'저장 버튼', r:'상세 입력 내용 저장', a:'클릭 시 현재 탭/속성 저장', c:'—' },
    'intakeComplete': { t:'종결 버튼', r:'사고건 처리 종결', a:'클릭 시 해당 건 종결 처리 (추정)', c:'종결 조건 충족 필요 (추정)' },
  },

  'image-system': {
    'btnRequest': { t:'대차/탑승 신청 버튼', r:'렌트·탑승 신청', a:'클릭 시 신청 모달 열림(공통)', c:'—' },
    'imgSearchInput': { t:'사진 검색 입력(사고번호·고객·차량)', r:'사고건/차량 검색', a:'input 시 applyImgSearch 실시간 필터, Enter 지원', c:'—' },
    'imgSearchClear': { t:'검색어 지우기(×) 버튼', r:'검색어 초기화', a:'클릭 시 검색 입력 비우고 목록 복원', c:'—' },
    'button|button|img-claim': { t:'사고건 목록 항목', r:'사진 열람 대상 사고 선택', a:'클릭 시 imgSelectedClaimId 변경, 사진/폴더 갱신', c:'(반복) 활성 항목 강조' },
    'button|button|folder-tab': { t:'사진 폴더 탭(사고사진 등)', r:'사진 분류 폴더 전환', a:'클릭 시 해당 폴더 사진 표시', c:'(반복) 활성 폴더 강조' },
    'button|button|folder-tab.empty': { t:'빈 폴더 탭(청구관련서류 0 등)', r:'사진 없는 분류 표시', a:'클릭 시 빈 상태 표시', c:'장수 0인 폴더' },
    'imgZoomBtn': { t:'확대보기 버튼', r:'선택 사진 확대', a:'클릭 시 "선택한 N장을 확대보기로 엽니다" 토스트(데모)', c:'선택 사진 없으면 0장' },
    'imgDownloadBtn': { t:'다운로드 버튼', r:'선택 사진 다운로드', a:'클릭 시 "N장을 다운로드합니다" 토스트(데모)', c:'데모 동작' },
    'imgSendBtn': { t:'문자 발송 버튼', r:'고객에게 이미지 발송', a:'클릭 시 openImageSendModal 열림(보안 링크/MMS 선택 발송)', c:'선택 사진과 대상 사고 필요' },
  },

  'approval-list': {
    'btnRequest': { t:'대차/탑승 신청 버튼', r:'렌트·탑승 신청', a:'클릭 시 신청 모달 열림(공통)', c:'—' },
    'apprSearchBtn': { t:'검색 버튼', r:'결재 목록 재조회', a:'클릭 시 renderClosingView 재렌더', c:'—' },
    'apprReset': { t:'초기화 버튼', r:'결재 검색 조건 초기화', a:'클릭 시 유형·상태·기간·검색어 초기화 후 재렌더', c:'—' },
    'apprType': { t:'결재 유형 선택', r:'추산/지급(종결)/면책종결/추가지급/업체관리 필터', a:'change 시 apprType 반영, 재렌더', c:'—' },
    'apprStatus': { t:'결재 상태 선택', r:'상신중/결재완료/반려/상신취소 필터', a:'change 시 apprStatus 반영, 재렌더', c:'—' },
    'apprFrom': { t:'조회 시작일', r:'결재 기간 하한', a:'change 시 apprFrom 반영, 재렌더', c:'—' },
    'apprTo': { t:'조회 종료일', r:'결재 기간 상한', a:'change 시 apprTo 반영, 재렌더', c:'—' },
    'apprSearch': { t:'담당자/사고번호 검색 입력', r:'담당자명·사고번호 like 검색', a:'input 시 apprQuery 실시간 필터', c:'—' },
    'button|button|appr-card': { t:'결재 유형 요약 카드', r:'유형별 건수 표시 + 필터', a:'클릭 시 apprType=카드 key 로 필터', c:'(반복 x6) 활성 카드 강조' },
    'input|checkbox|': { t:'결재 행 선택 체크박스', r:'일괄 결재 대상 선택', a:'토글 시 대상 선택 (추정)', c:'(반복)' },
  },

  'assignment-management': {
    'btnRequest': { t:'대차/탑승 신청 버튼', r:'렌트·탑승 신청', a:'클릭 시 신청 모달 열림(공통)', c:'—' },
    'assignSearchBtn': { t:'검색 버튼', r:'담당자 목록 조회', a:'클릭 시 조건으로 담당자 목록 재조회 (추정)', c:'—' },
    'assignSimBtn': { t:'시뮬레이션 버튼', r:'순환배당 시뮬레이션', a:'클릭 시 openAssignSim 모달 열림(배당 결과 미리보기)', c:'—' },
    'assignSaveBtn': { t:'저장 버튼', r:'전결권한·배당 규칙 저장', a:'클릭 시 저장 처리 실행', c:'—' },
    'assignRegion': { t:'권역 선택', r:'수도권/중부권 필터', a:'change 시 apply() 목록 필터', c:'—' },
    'assignDept': { t:'팀 선택', r:'Claim운영1/2팀 필터', a:'change 시 apply() 목록 필터', c:'—' },
    'assignCenter': { t:'센터 선택', r:'강남/분당센터 필터', a:'change 시 apply() 목록 필터', c:'—' },
    'assignName': { t:'담당자/사번 검색 입력', r:'담당자명·사번 검색', a:'input 시 apply() 실시간 필터', c:'—' },
    'assignDate': { t:'기준일 입력', r:'배당 기준 날짜', a:'날짜 선택 시 기준일 반영', c:'—' },
    'assignBulkBtn': { t:'조회목록 적용 버튼', r:'일 배당한도 일괄 적용', a:'클릭 시 applyBulkDailyLimit 실행', c:'조회된 목록 대상' },
    'assignBulkDaily': { t:'일 배당한도 입력', r:'일괄 적용할 한도값', a:'입력 후 적용 버튼 또는 Enter 시 applyBulkDailyLimit', c:'숫자 입력' },
    'input|checkbox|': { t:'담당자 행 선택/속성 체크박스', r:'담당자 선택 또는 배당중지 등 속성', a:'토글로 대상/속성 반영 (추정)', c:'(반복)' },
  },

  'vendor-inquiry': {
    'btnRequest': { t:'대차/탑승 신청 버튼', r:'렌트·탑승 신청', a:'클릭 시 신청 모달 열림(공통)', c:'—' },
    'vSearchBtn': { t:'검색 버튼', r:'협력업체 조회', a:'클릭 시 검색 유형·키워드로 업체 조회', c:'—' },
    'vSearchType': { t:'검색 유형 선택', r:'업체명/사업자번호/BP ID/제휴사/지점코드/대표자명', a:'선택 후 키워드와 함께 검색', c:'—' },
    'vSearchKeyword': { t:'검색 키워드 입력', r:'검색 유형에 대응하는 값', a:'입력 후 검색 실행', c:'—' },
    'vVendorKind': { t:'업체 구분 선택', r:'정비/부품/유리/렌트/실런트 업체 구분', a:'선택 시 업체 종류 필터', c:'—' },
    'button|button|lg-abtn.primary': { t:'저장 버튼(섹션별)', r:'업체 정보 저장', a:'클릭 시 해당 섹션 값 저장 (추정)', c:'(반복 x4)' },
    'button|button|lg-mini.gray': { t:'정보수정 버튼', r:'업체 상세 정보 수정 모드', a:'클릭 시 수정 활성화 (추정)', c:'(반복 x6)' },
    'button|button|lg-mini': { t:'＋ 행추가 버튼', r:'표에 행 추가', a:'클릭 시 신규 행 추가 (추정)', c:'—' },
    'input|checkbox|': { t:'선택/여부 체크박스', r:'항목 선택 또는 사용여부', a:'토글로 상태 반영 (추정)', c:'(반복)' },
    'select||lg-sel': { t:'구분 선택(담당 구분 등)', r:'셀 단위 구분값', a:'선택 시 값 반영', c:'(반복)' },
    'input||lg-in': { t:'표 셀 입력 필드', r:'업체 계약/수가/지급처 상세값', a:'입력값 반영', c:'(반복 다수)' },
    'input|date|lg-in.vend': { t:'계약 만료일 입력', r:'계약 종료일(예: 9999-12-31)', a:'날짜 입력 시 반영', c:'—' },
    'button|button|v-pro': { t:'실적관리 버튼 (Pro)', r:'업체 실적 관리 진입', a:'클릭 시 실적관리 기능 (Pro)', c:'(반복 x2) Pro 기능' },
    'vEvalBtn': { t:'선정평가 버튼', r:'협력업체 선정평가 열기', a:'클릭 시 vendor-eval 평가 화면/모달 오픈', c:'—' },
    'input|radio|': { t:'옵션 라디오(국산/외산 등)', r:'단일 선택 옵션', a:'선택 시 값 반영', c:'(반복)' },
    'vOriginSel': { t:'원산지 선택', r:'국산/외산 구분', a:'선택 시 수가율 기준 반영', c:'—' },
    'vOriginRate': { t:'수가율 입력', r:'원산지별 적용 요율(%)', a:'입력값 반영', c:'—' },
    'vBulkApply': { t:'일괄적용 버튼', r:'요율 일괄 적용', a:'클릭 시 대상 행에 요율 일괄 반영 (추정)', c:'—' },
    'input|password|lg-in': { t:'비밀번호 입력', r:'결재/승인용 인증', a:'입력값 인증에 사용 (추정)', c:'마스킹' },
    'textarea||lg-ta': { t:'결재 의견 입력', r:'상신 의견', a:'상신 시 의견 반영', c:'—' },
    'button|button|lg-abtn': { t:'상신 버튼', r:'변경 내용 결재 상신', a:'클릭 시 상신 처리 (추정)', c:'(반복 x4)' },
  },

  'vendor-eval': {
    'veClose': { t:'닫기 버튼', r:'평가 화면 닫기', a:'클릭 시 창/모달 닫기', c:'—' },
    'button|button|ve-tab': { t:'평가 탭(①평가항목/②배점 등)', r:'평가 설정 단계 전환', a:'클릭 시 해당 탭 표시', c:'(반복 x3) 활성 탭 강조' },
    'button|button|ve-btn': { t:'+ 항목추가 버튼', r:'평가 항목 추가', a:'클릭 시 새 항목 행 추가', c:'—' },
    'button|button|ve-btn.gray': { t:'- 항목삭제 버튼', r:'평가 항목 삭제', a:'클릭 시 항목 제거', c:'(반복 x3)' },
    'select||ve-sel': { t:'평가 유형 선택(YESNO/SCALE/CUSTOM)', r:'항목 응답 방식', a:'선택 시 항목 입력 형태 변경', c:'(반복 다수)' },
    'input||ve-in': { t:'평가 항목명 입력', r:'항목 명칭', a:'입력값 반영', c:'(반복 다수)' },
    'input|number|ve-in.ve-num': { t:'배점 입력', r:'항목 점수/가중치', a:'숫자 입력 시 배점 반영', c:'(반복)' },
    'button|button|ve-yn': { t:'Y/N 토글 버튼', r:'예/아니오 응답', a:'클릭 시 Y↔N 전환', c:'(반복 다수)' },
    'input|radio|': { t:'옵션 라디오', r:'단일 선택 응답', a:'선택 시 값 반영', c:'(반복)' },
    'button|button|ve-btn.small': { t:'+ 옵션추가 버튼', r:'선택 옵션 추가', a:'클릭 시 옵션 행 추가', c:'—' },
    'button|button|ve-mini.gray': { t:'삭제 버튼(옵션)', r:'옵션/행 삭제', a:'클릭 시 해당 항목 제거', c:'(반복 x2)' },
    'button|button|ve-mini': { t:'▲ 순서 이동 버튼', r:'항목 순서 조정', a:'클릭 시 위/아래 이동 (추정)', c:'(반복 x4)' },
  },

  'message-send': {
    'roleSel': { t:'역할 선택(담당자/시스템담당자)', r:'사용자 역할 전환', a:'change 시 state.role 변경, 화면 재렌더(관리자 전용 버튼 노출 등)', c:'ADMIN 시 표준문구설정 노출' },
    'input|checkbox|': { t:'수신 채널/대상 체크박스', r:'발송 채널 또는 수신자 선택', a:'토글로 대상 반영', c:'(반복 x3)' },
    'button|button|tpl': { t:'템플릿 버튼(운전자확인 등)', r:'대표 문구 템플릿 선택', a:'클릭 시 내용란 자동 채움(data-tpl)', c:'(반복 x12)' },
    'mAdd': { t:'번호 추가 버튼', r:'수신자 행 추가', a:'클릭 시 이름·휴대폰 입력 행 추가', c:'—' },
    'mName': { t:'이름 입력', r:'수신자 성명', a:'입력값 수신자에 반영', c:'—' },
    'mPhone': { t:'휴대폰번호 입력', r:'수신자 연락처', a:'입력값 수신자에 반영', c:'형식 예: 010-1234-5678' },
    'button|button|lbtn': { t:'주소록/템플릿설정 버튼', r:'주소록·개인 템플릿 관리 열기', a:'클릭 시 data-open 대상 모달 오픈', c:'(반복 x2)' },
    'contentTa': { t:'보낼 내용 입력(textarea)', r:'발송 본문', a:'input 시 state.content 갱신, 글자수 등 메타 갱신', c:'읽기전용 아닐 때만 편집' },
    'sendBtn': { t:'문자 발송 버튼', r:'발송 실행', a:'클릭 시 발송 확인 모달(openConfirm) 열림 → 확인 시 doSend', c:'수신자·내용 필요' },
  },

  'ai-dashboard': {
    'btnRequest': { t:'대차/탑승 신청 버튼', r:'렌트·탑승 신청', a:'클릭 시 신청 모달 열림(공통)', c:'—' },
    'btnAiRequest': { t:'AI 검토요청 버튼', r:'AI 심사 요청 생성', a:'클릭 시 openRequestModal(AI 검토요청 모달) 열림 → 대상 선택 후 startAnalysis 로 분석 시작', c:'대상 사고건 선택 필요' },
    'button|button|ai-scard': { t:'AI 요약 카드(검토대상 등)', r:'AI 검토 상태별 건수 표시 + 필터', a:'클릭 시 cardFilter 적용, 리스트 필터', c:'(반복 x3) 활성 카드 강조' },
    'button|button|ai-scard.warn': { t:'보류·대기 카드', r:'보류/자료대기/분석실패 건수 강조', a:'클릭 시 해당 상태로 필터', c:'경고색 표기' },
    'fReset': { t:'초기화 버튼', r:'AI 필터 초기화', a:'클릭 시 단계·판정·점수·확신도·검색어 초기화 후 재렌더', c:'—' },
    'fStage': { t:'단계 필터 선택', r:'대기중/수리승인/손해사정/완료', a:'change 시 filters 반영, renderAiList', c:'—' },
    'fDecision': { t:'판정 필터 선택', r:'자료대기/분석대기/적정 등', a:'change 시 filters 반영, renderAiList', c:'—' },
    'fScore': { t:'AI 점수 필터 선택', r:'점수 구간(85↑ 등)', a:'change 시 filters 반영, renderAiList', c:'—' },
    'fConf': { t:'확신도 필터 선택', r:'확신도 구간(90%↑ 등)', a:'change 시 filters 반영, renderAiList', c:'—' },
    'fSearch': { t:'통합 검색 입력', r:'접수번호·차량·업체 검색', a:'input 시 filters.q 반영, renderAiList', c:'—' },
    'button|button|btn-move': { t:'이동 버튼(행)', r:'해당 사고 상세로 이동', a:'클릭 시 data-move 대상으로 이동 (추정)', c:'(반복 x11)' },
    'button|button|link-id': { t:'접수번호 링크(행)', r:'AI 검토 상세 열기', a:'클릭 시 data-detail 로 상세 표시', c:'(반복 x11)' },
  },

  'smart-claims-demo': {
    'a|href|smart-claims.html': { t:'모드변경·실제 화면 링크', r:'실제 미결일괄조회로 전환', a:'클릭 시 smart-claims.html 로 이동', c:'시연 모드 종료' },
    'button|button|nav-item': { t:'좌측 네비 항목', r:'화면 이동 메뉴', a:'클릭 시 해당 화면 이동', c:'(반복) 활성 항목 강조' },
    'stageSelect': { t:'단계 선택 드롭다운', r:'단계 필터', a:'change 시 단계 필터 적용', c:'시연 데이터 기준' },
    'input|checkbox|': { t:'조치유형 체크박스', r:'조치유형 필터', a:'토글로 필터 반영', c:'(반복 x5)' },
    'button|button|btn-reset': { t:'초기화 버튼', r:'필터 초기화', a:'클릭 시 조건 초기화', c:'—' },
    'button|button|btn-search': { t:'조회 버튼', r:'재조회', a:'클릭 시 리스트 재조회', c:'—' },
    'shopInput': { t:'정비공장명 검색 입력', r:'정비공장 부분검색', a:'입력 시 필터', c:'—' },
    'searchInput': { t:'통합 검색 입력', r:'통합 like 검색', a:'입력 시 필터', c:'—' },
    'button|button|': { t:'계획 필터 탭(전체/긴급/관심)', r:'별점 상태 필터', a:'클릭 시 필터 적용', c:'(반복 x3)' },
    'btnPlay': { t:'자동 처리 시작 버튼', r:'시연 자동 재생/일시정지 토글', a:'클릭 시 running이면 pause(), 아니면 play(): setInterval(tick, tickMs)로 자동 처리 진행. 라벨 "처리 진행중…/이어서 재생"으로 변경', c:'대기건 0이면 먼저 reset()' },
    'btnReset': { t:'리셋 버튼', r:'시연 초기화', a:'클릭 시 reset(): 타이머 정지, seed()·fullRender()로 초기 상태 복원', c:'—' },
    'speed': { t:'재생 속도 슬라이더', r:'자동 처리 간격 조절', a:'input 시 tickMs=1280-값, 라벨 "빠름/보통/느림" 갱신', c:'값 클수록 빠름' },
    'loop': { t:'반복 재생 체크박스', r:'시연 반복 여부', a:'체크 시 완료 후 반복 재생 (추정)', c:'—' },
    'selectAll': { t:'전체선택 체크박스', r:'현재 페이지 전체 선택', a:'체크 시 페이지 항목 선택', c:'—' },
    'button|button|star-btn': { t:'계획(별점) 토글', r:'행별 긴급/관심 표시', a:'클릭 시 상태 순환', c:'(반복 x28)' },
    'input|checkbox|row-check': { t:'행 선택 체크박스', r:'개별 건 선택', a:'토글로 선택', c:'(반복 x28)' },
    'btnReplay': { t:'다시 재생 버튼', r:'처음부터 재생', a:'클릭 시 reset() 후 150ms 뒤 play()', c:'완료 오버레이에서 노출' },
  },
};
